### ISSUE TITLE
small suggestion: add a default value for date

### ISSUE THREAD

**Issue by jimniels** [kentcdodds/advanced-remix#2]
Small piece of feedback from doing the workshop.

Whenever I'm testing the "new deposit" functionality in the exercises, I'm constantly having to type in an amount, choose a date, then hit submit. Entering the date can get a bit tiresome. 

<img width="694" alt="CleanShot 2022-05-24 at 11 42 07@2x" src="https://user-images.githubusercontent.com/1316441/170098753-58646ed4-7d19-4882-b1f4-4b2c7998b70e.png">

Maybe you could default it to have a value, that way when you're doing the exercise and testing your code, you don't have to fumble through choosing a date in the UI each time you want to test posting the form data. Something like this [here](https://github.com/kentcdodds/advanced-remix/blob/c7c9631a2c9e80c3c3403a33aaf9bdb59353daf5/final/01-non-nav-mutations/app/routes/__app/sales/invoices/%24invoiceId.tsx#L229):

```
<input type="date" defaultValue={new Date().toISOString().slice(0, 10)} />
```

<img width="686" alt="CleanShot 2022-05-24 at 11 38 18@2x" src="https://user-images.githubusercontent.com/1316441/170098100-19a7ed36-3efa-45ec-ac08-08a8dafb9cf3.png">

**Comment by jimniels** [comment]
Ha! And now in the next exercise, I see the value of keeping the date field without a value (for error handling and focus). So I guess disregard this.

**Comment by kentcdodds** [comment]
Thanks anyway Jim!
